name: Vue CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:unit --if-present

      - name: Build application
        run: npm run build

      - name: Start preview server for E2E
        run: npm run preview &

      - name: Wait for preview server
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run End-to-End Tests
        run: npx cypress run --config baseUrl=http://localhost:4173

  security:
    runs-on: ubuntu-latest
    needs: build
    name: Security Scanning

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security Vulnerability Scan
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Dependency Security Check
        uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'
        continue-on-error: true

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
        continue-on-error: true

      - name: Security Report Comment (PR only)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🔒 Security scanning completed! Check logs for vulnerability details.'
            })

  lighthouse:
    runs-on: ubuntu-latest
    needs: build
    name: Performance Monitoring

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Start preview server
        run: npm run preview &

      - name: Wait for server
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: false
          temporaryPublicStorage: true
        continue-on-error: true

      - name: Performance Report Comment (PR only)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Lighthouse performance check completed!'
            })

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security, lighthouse]
    name: Deploy to Production

    steps:
      - name: Check if main branch
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            echo "⏭️ Skipping deployment - not main branch"
            echo "Current branch: ${{ github.ref }}"
            echo "✅ All checks passed, ready for production when merged to main"
            exit 0
          fi

      - uses: actions/checkout@v4
        if: github.ref == 'refs/heads/main'

      - name: Set up Node.js
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        if: github.ref == 'refs/heads/main'
        run: npm ci

      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

      - name: Deployment Success Notification
        if: github.ref == 'refs/heads/main'
        run: |
          echo "✅ Deployment successful!"
          echo "🚀 Live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
