name: Vue CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test & Quality Check

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test:unit --if-present

      - name: Run coverage report
        run: npm run test:coverage --if-present

      - name: Build application
        run: npm run build

      - name: Start preview server for E2E
        run: npm run preview &

      - name: Wait for preview server
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run End-to-End Tests
        run: npx cypress run --config baseUrl=http://localhost:4173

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    name: Performance Monitoring
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Start preview server
        run: npm run preview &

      - name: Wait for server
        run: npx wait-on http://localhost:4173 --timeout 60000

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Performance Report Comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Lighthouse performance check completed! Check artifacts for detailed report.'
            })

  deploy:
    runs-on: ubuntu-latest
    needs: [test, lighthouse]
    name: Deploy to Production
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for production
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist

      - name: Deployment Success Notification
        run: |
          echo "✅ Deployment successful!"
          echo "🚀 Live at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          echo "📊 Performance monitoring active"

      - name: Deployment Failure Notification
        if: failure()
        run: |
          echo "❌ Deployment failed!"
          echo "🔍 Check logs above for details"
          echo "📧 Team has been notified"
